### PR TITLE
Initial dnf-automatic cookbook

### PR DESCRIPTION
**Pull request by ramereth**
This installs and manages the dnf-automatic package and automatically enables
the time server.

### CODE REVIEW

**Comment by ramereth** [comment]
[dnf-automatic (new)](https://trello.com/c/2UPx3xNa/1432-dnf-automatic-new)

**Comment by ramereth** [comment]
!bump major

**Comment by ramereth** [comment]
!bump major *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v1.0.0.  Have a nice day!

**Pull request merged**
