### PR TITLE
Remove CentOS Stream 8 references

### PR DESCRIPTION
**Pull request by ArtofBugs**

### CODE REVIEW

**Review by ramereth — APPROVED** [review]
Patch bump

**Comment by ArtofBugs** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.0.4.  Have a nice day!

**Comment by ArtofBugs** [comment]
Manual PR https://github.com/osuosl/chef-repo/pull/4182

**Pull request merged**
